In [1]:
import pandas as pd


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Tariqueakhtar/Machine-Learning/master/Car_Pricing/CarPrice_Assignment.csv')

In [5]:
df = pd.read_csv('CarPrice_Assignment.csv',)

In [6]:
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [9]:
df.to_csv('mycsv.csv', index=False, sep = "|")

In [10]:
data  = [[1,2,3],
        [4,5,6]]

In [13]:
pd.DataFrame(data, columns=['A', 'B', 'C'], index = ['x', 'y'])

A  B  C
x  1  2  3
y  4  5  6

In [14]:
data = {'A':[1,2],
       "B": [3,4]}

In [16]:
df = pd.DataFrame(data)

In [19]:
df1 = pd.DataFrame([[1,"A"],
             [2,"B"]], columns=['col1', 'col2'])

In [22]:
df2 = pd.DataFrame([["A", 3], ["B", 4]], columns=['col2', 'col3'])

In [27]:
mergeddf = pd.merge(df1,df2, on= 'col2', how = 'inner')

In [28]:
mergeddf



col1 col2  col3
0     1    A     3
1     2    B     4

In [33]:
pd.merge(df1,df1, how='left')

col1 col2
0     1    A
1     2    B

In [36]:
df = pd.DataFrame([[2, "A"],
             [3, "B"],
             [1, "A"]], columns=['col1', 'col2'])

In [37]:
df

col1 col2
0     2    A
1     3    B
2     1    A

In [39]:
df.sort_index(ascending=False)

col1 col2
2     1    A
1     3    B
0     2    A

In [40]:
df

col1 col2
0     2    A
1     3    B
2     1    A

In [41]:
df.sort_values(by='col1')

col1 col2
2     1    A
0     2    A
1     3    B

In [46]:
df1= pd.DataFrame([[1,"A"],[2,"B"]], columns=['col1', 'col2'])

In [50]:
df2 = pd.DataFrame([["A", 3],["B",4]], columns=['col3', 'col4'])

In [53]:
pd.concat((df1,df2),axis=1)

col1 col2 col3  col4
0     1    A    A     3
1     2    B    B     4

In [54]:
df1

col1 col2
0     1    A
1     2    B

In [55]:
df.rename(columns={'col1':'col3',
                  'col2':'col4'})

col3 col4
0     2    A
1     3    B
2     1    A

In [63]:
df1['col5'] = np.nan

In [64]:
df1

col1 col2  col5
0     1    A   NaN
1     2    B   NaN

In [62]:
import numpy as np

In [67]:
df1['col5'] = df['col1'] + 15

In [68]:
df1

col1 col2  col5
0     1    A    17
1     2    B    18

In [70]:
df1['col6'] = df1['col1'] + 2

In [71]:
df1

col1 col2  col5  col6
0     1    A    17     3
1     2    B    18     4

In [74]:
df = pd.DataFrame([[1,"A"],[2,"B"],[2,"A"],[3,"C"]], columns=['COL1', 'COL2'])

In [78]:
df.rename(columns={'COL1':'A', "COL2":'B'}, inplace=True)

In [79]:
df

A  B
0  1  A
1  2  B
2  2  A
3  3  C

In [82]:
df[df.A>1]

A  B
1  2  B
2  2  A
3  3  C

In [87]:
df[df['A'].isin([1,2])]

A  B
0  1  A
1  2  B
2  2  A

In [86]:
df['A']

0    1
1    2
2    2
3    3
Name: A, dtype: int64

In [88]:
df

A  B
0  1  A
1  2  B
2  2  A
3  3  C

In [90]:
df.drop(columns='B', inplace=True)

In [92]:
df

A
0  1
1  2
2  2
3  3

In [93]:
    df

A
0  1
1  2
2  2
3  3

In [96]:
df= pd.DataFrame([[1,"A"],[2,"B"],[3,"A"],[4,"C"]], columns=['col1', 'col2'])

In [97]:
df

col1 col2
0     1    A
1     2    B
2     3    A
3     4    C

In [105]:
df.groupby('col2')['col1'].sum()

col2
A    4
B    2
C    4
Name: col1, dtype: int64

In [106]:
df

col1 col2
0     1    A
1     2    B
2     3    A
3     4    C

In [109]:
df.col2.unique()

array(['A', 'B', 'C'], dtype=object)

In [110]:
df.col2.unique()

array(['A', 'B', 'C'], dtype=object)

In [112]:
df['col2'].nunique()

3

In [116]:
df = pd.DataFrame([[1,"A"],
             [2,np.nan],
             [3,np.nan]], columns=['col1', 'col2'])

In [119]:
df.col2.fillna('B', inplace=True)

In [120]:
df

col1 col2
0     1    A
1     2    B
2     3    B

In [121]:

def test(number):
    return number + 2 

In [122]:
test(5)

7

In [124]:

df = pd.DataFrame([[1,"A"], [2,"B"]], columns=['col1', 'col2'])

In [127]:
df['col3'] = df['col1'].apply(test)

In [128]:
df

col1 col2  col3
0     1    A     3
1     2    B     4

In [129]:
df

col1 col2  col3
0     1    A     3
1     2    B     4

In [143]:
df = pd.DataFrame([[1,"A"],[2,"B"], [1,"A"],[2,"B"],[3,'C'], [4,"D"]], columns=['col1', 'col2'])

In [135]:
df.drop_duplicates(inplace=True)

In [137]:
df

col1 col2
0     1    A
1     2    B

In [144]:
df

col1 col2
0     1    A
1     2    B
2     1    A
3     2    B
4     3    C
5     4    D

In [147]:
df.col2.value_counts()

B    2
A    2
C    1
D    1
Name: col2, dtype: int64

In [149]:
df['col2'].value_counts()

B    2
A    2
C    1
D    1
Name: col2, dtype: int64

In [150]:
df.shape

(6, 2)

In [151]:
import numpy as np
import pandas as pd

In [180]:
a1 = [1,2,3]

In [181]:
d1 = np.array(a1, dtype = 'float32')

In [182]:
type(a)

list

In [166]:
a = [[1,2,3], [4,5,6]]

In [178]:
d = np.array(a,dtype = 'float32')

In [179]:
d

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [169]:
d1

array([1, 2, 3])

In [170]:
type(d)

numpy.ndarray

In [171]:
type(d1)

numpy.ndarray

In [172]:
d.ndim

2

In [173]:
d1.ndim

1

In [183]:
d.dtype

dtype('float32')

In [184]:
d1.dtype

dtype('float32')

In [185]:
d = [1,5,6]

In [189]:
f = np.array(d, dtype = np.float64)

In [190]:
f.dtype

dtype('float64')

In [193]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [196]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [197]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [198]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [201]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [204]:
np.arange(0,10,5)

array([0, 5])

In [205]:
np.arange(5,11,1)

array([ 5,  6,  7,  8,  9, 10])

In [206]:
np.arange(5,11,2)

array([5, 7, 9])

In [207]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [211]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [219]:
np.random.randint(5,16,5)


array([10, 11, 10, 13,  6])

In [234]:
np.random.random(12)

array([0.10292751, 0.86917759, 0.25917799, 0.36460738, 0.91783381,
       0.74454815, 0.12278425, 0.09141712, 0.8888355 , 0.99041864,
       0.28219942, 0.34719174])

In [242]:
x = pd.Series([1,2,3,4],name = 'col')

In [243]:
x

0    1
1    2
2    3
3    4
Name: col, dtype: int64

In [244]:
np.array(x)

array([1, 2, 3, 4], dtype=int64)

In [245]:
 s = pd.Series([1,2,3,4,5,6],name = 'col')

In [246]:
np.asarray(s)

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [248]:
a = np.ones((2,3))

In [249]:
np.shape(a)

(2, 3)

In [250]:
a.shape

(2, 3)

In [252]:
a = np.arange(18)

In [253]:
a.shape

(18,)

In [255]:
a.reshape((3,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [256]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [258]:
a = np.reshape(a,(6,3))

In [259]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [260]:
a.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [262]:
b = np.arange(12)

In [264]:
b = np.reshape(b, (6,2))

In [265]:
b.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [266]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [267]:
np.transpose(b)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [269]:
a = np.array([[1,2],[3,4]])

In [271]:
b = np.array([[5,6]])

In [277]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [281]:
a.shape

(2, 2)

In [280]:
b.shape

(1, 2)

In [283]:
n = np.concatenate((a,b.T), axis = 1)

In [284]:
n

array([[1, 2, 5],
       [3, 4, 6]])

In [285]:
a

array([[1, 2],
       [3, 4]])

In [286]:
b

array([[5, 6]])

In [289]:
f = np.concatenate((a,b), axis = None)

In [290]:
a

array([[1, 2],
       [3, 4]])

In [291]:
b

array([[5, 6]])

In [292]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [294]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [295]:
a

array([[1, 2],
       [3, 4]])

In [296]:
a.flatten()

array([1, 2, 3, 4])

In [303]:
a = np.array([[1,2,3],[1,2,3],[2,3,4]])

In [304]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [306]:
np.unique(a,axis = 0)

array([[1, 2, 3],
       [2, 3, 4]])

In [308]:
f = np.array([[1,1,3], [1,1,3],[1,1,4]])

In [310]:
np.unique(f, axis=1)

array([[1, 3],
       [1, 3],
       [1, 4]])

In [313]:
a = np.array([[[0],[1],[2]]])

In [314]:
a.ndim

3

In [315]:
a.shape

(1, 3, 1)

In [317]:
np.squeeze(a).shape

(3,)

In [320]:
type(a)

numpy.ndarray

In [321]:
type(a.tolist())

list

In [322]:
np.arange(3)

array([0, 1, 2])

In [324]:
a = np.array([1,2,3])

In [325]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [326]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [327]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [329]:
a = np.linspace(1,2,5)

In [330]:
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [331]:
np.floor(a)

array([1., 1., 1., 1., 2.])

In [332]:
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [333]:
np.ceil(a)

array([1., 2., 2., 2., 2.])

In [334]:
np.rint(a)

array([1., 1., 2., 2., 2.])

In [336]:
np.round(a,decimals=2)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [338]:
a = np.linspace(1,2,7)

In [339]:
a

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [340]:
np.rint(a,)

array([1., 1., 1., 2., 2., 2., 2.])

In [342]:
np.round(a, decimals=3)

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   ])

In [344]:
a = np.arange(1,6)

In [346]:
np.exp(a).round(2)

array([  2.72,   7.39,  20.09,  54.6 , 148.41])

In [347]:
a


array([1, 2, 3, 4, 5])

In [349]:
np.log(a).round(3)

array([0.   , 0.693, 1.099, 1.386, 1.609])

In [351]:
a = np.array([[1,2],[3,4]])

In [352]:
a

array([[1, 2],
       [3, 4]])

In [353]:
np.sum(a)

10

In [354]:
np.sum(a, axis = 0)

array([4, 6])

In [355]:
np.sum(a, axis = 1)

array([3, 7])

In [356]:
np.prod(a)

24

In [357]:
np.product(a, axis = 0)

array([3, 8])

In [359]:
np.prod(a, axis = 0)

array([3, 8])

In [360]:
np.prod(a,axis=1)

array([ 2, 12])

In [362]:
a

array([[1, 2],
       [3, 4]])

In [364]:
np.sqrt(a).round(2)

array([[1.  , 1.41],
       [1.73, 2.  ]])

In [365]:
a

array([[1, 2],
       [3, 4]])

In [368]:
b = np.array([[1,1], [1,1]])

In [369]:
np.dot(a,b)

array([[3, 3],
       [7, 7]])

In [370]:
b

array([[1, 1],
       [1, 1]])

In [371]:
a*b

array([[1, 2],
       [3, 4]])

In [372]:
a@b

array([[3, 3],
       [7, 7]])

In [373]:
np.matmul(a,b)

array([[3, 3],
       [7, 7]])

In [375]:

a = np.arange(-4,5)

In [376]:
np.linalg.norm(a)

7.745966692414834

In [377]:
np.linalg.norm(a,ord=1)

20.0

In [379]:
a = np.array([[1,4], [3,1]])

In [380]:
a

array([[1, 4],
       [3, 1]])

In [381]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [383]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [384]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [386]:
x = np.array([3,1,2])

In [388]:
np.argsort(x, axis=None)

array([1, 2, 0], dtype=int64)

In [401]:
a = np.random.randint(1,20,10)

In [402]:
a = a.reshape(2,5)

In [403]:
np.argmax(a, axis=0)

array([0, 0, 1, 0, 1], dtype=int64)

In [397]:
a

array([[10,  6,  9,  7, 14],
       [12,  4, 11,  9, 10]])

In [399]:
a.flatten()

array([10,  6,  9,  7, 14, 12,  4, 11,  9, 10])

In [404]:
np.argmax(a, axis=1)

array([1, 4], dtype=int64)

In [405]:
a

array([[ 3, 11,  3,  9, 10],
       [ 1,  6, 14,  2, 16]])

In [410]:
ind = np.unravel_index(np.argmax(a), a.shape)

In [407]:
a.flatten()

array([ 3, 11,  3,  9, 10,  1,  6, 14,  2, 16])

In [411]:
ind

(1, 4)

In [413]:
a = np.random.randint(1,20,10).reshape(2,5)

In [414]:
a

array([[16,  2, 11, 16,  4],
       [14, 10, 15,  3,  8]])

In [415]:
np.argmin(a)

1

In [416]:
np.argmin(a, axis=0)

array([1, 0, 0, 1, 0], dtype=int64)

In [417]:
np.argmin(a,axis=1)

array([1, 3], dtype=int64)

In [419]:
a = np.random.randint(-10,10,10)

In [421]:
np.where(a<0,0,a)

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [422]:
a

array([  2, -10,  -7,  -5,  -6,  -6, -10,  -4, -10,   0])

In [426]:
a = np.array([[3,0,0],[0,4,0],[5,6,0]])

In [427]:
np.nonzero(a)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [429]:
a = np.array([[1,2], [3,4]])

In [430]:
a

array([[1, 2],
       [3, 4]])

In [432]:
np.mean(a, axis=0)

array([2., 3.])

In [433]:
np.mean(a,axis=1)

array([1.5, 3.5])

In [434]:
a

array([[1, 2],
       [3, 4]])

In [435]:
np.median(a)

2.5

In [436]:
np.median(a,axis=0)

array([2., 3.])

In [437]:
np.median(a,axis=1)

array([1.5, 3.5])

In [438]:
a

array([[1, 2],
       [3, 4]])

In [440]:
np.mod(5,2)

1

In [441]:
a

array([[1, 2],
       [3, 4]])

In [442]:
np.std(a)

1.118033988749895

In [443]:
np.std(a, axis=0)

array([1., 1.])

In [444]:
np.std(a,axis=1)

array([0.5, 0.5])