In [1]:
#Translating SQL Queries to Pandas Operations

In [2]:
import pandas as pd

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/Avee-81/SQL-to-Pandas/main/data.csv')

In [3]:
!pip install ipython-sql

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13714 sha256=6c39b12e09c523ee265e665b89c79256dc421204faa232ae918938e79d8ae7cd
  Stored in directory: c:\users\skme2\appdata\local\pip\cache\wheels\48\6d\77\9517cb933af254f51a446f1a5ec9c2be3e45f17384940bce68
Successfully built prettytable


In [4]:
%load_ext sql

In [5]:
%sql sqlite://

In [6]:
import numpy as np

In [22]:
df

ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2        10/03/20
1   2      Julie    Miller      F   12000      2        14/01/20
2   3     Rachel      Bray      F    9000      1        09/03/20
3   4      Priti   Agarwal      F   10000      2        01/03/20
4   5      David       Cox      M    5000      1        28/05/20
5   6      Helly     Raval      F    8000      1        19/06/20
6   7       John     Frank      M   13000      3        12/11/19
7   8       Mark  Franklin      M   13500      3        12/11/19
8   9   Cristina       Rel      F   15000      4        22/09/19
9  10      Brock    Murray      M   11000      2        13/02/20

In [23]:
df.info

<bound method DataFrame.info of    ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2        10/03/20
1   2      Julie    Miller      F   12000      2        14/01/20
2   3     Rachel      Bray      F    9000      1        09/03/20
3   4      Priti   Agarwal      F   10000      2        01/03/20
4   5      David       Cox      M    5000      1        28/05/20
5   6      Helly     Raval      F    8000      1        19/06/20
6   7       John     Frank      M   13000      3        12/11/19
7   8       Mark  Franklin      M   13500      3        12/11/19
8   9   Cristina       Rel      F   15000      4        22/09/19
9  10      Brock    Murray      M   11000      2        13/02/20>

In [24]:
df.date_of_joining.dtype

dtype('O')

In [25]:
df["date_of_joining"] = pd.to_datetime(df.date_of_joining)

In [26]:
df.date_of_joining.dtype

dtype('<M8[ns]')

In [28]:
df.date_of_joining.dtype

dtype('<M8[ns]')

In [35]:
%%sql
drop table if exists employee;
create table employee(ID integer,
                     first_name varchar(20),
                     last_name varchar(20),
                     gender varchar(2),
                     salary integer,
                     level integer,
                      date_of_joining date);
insert into employee 
values(1, 'Peter',    'Sanders',  'M', 10000, 2, '2020-03-10'),
       (2, 'Julie',    'Miller',   'F', 12000, 2, '2020-01-14'),
       (3, 'Rachel',   'Bray',     'F', 9000,  1, '2020-03-09'),
       (4, 'Priti',    'Agarwal',  'F', 10000, 2, '2020-03-01'),
       (5, 'David',    'Cox',      'M', 5000,  1, '2020-05-28'),
       (6, 'Helly',    'Raval',    'F', 8000,  1, '2020-06-19'),
       (7, 'John',     'Frank',    'M', 13000, 3, '2019-11-12'),
       (8, 'Mark',     'Franklin', 'M', 13500, 3, '2019-11-12'),
       (9, 'Cristina', 'Rel',      'F', 15000, 4, '2019-09-22'),
       (10, 'Brock',   'Murray',   'M', 11000, 2,' 2020-02-13');

 * sqlite://
Done.
Done.
10 rows affected.


[]

In [38]:
%%sql
select * from employee limit 5;

 * sqlite://
Done.


[(1, 'Peter', 'Sanders', 'M', 10000, 2, '2020-03-10'),
 (2, 'Julie', 'Miller', 'F', 12000, 2, '2020-01-14'),
 (3, 'Rachel', 'Bray', 'F', 9000, 1, '2020-03-09'),
 (4, 'Priti', 'Agarwal', 'F', 10000, 2, '2020-03-01'),
 (5, 'David', 'Cox', 'M', 5000, 1, '2020-05-28')]

In [39]:
df.head(5)

ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2      2020-10-03
1   2      Julie    Miller      F   12000      2      2020-01-14
2   3     Rachel      Bray      F    9000      1      2020-09-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
4   5      David       Cox      M    5000      1      2020-05-28

In [44]:
%%sql
select *from employee where gender == 'F';

 * sqlite://
Done.


[(2, 'Julie', 'Miller', 'F', 12000, 2, '2020-01-14'),
 (3, 'Rachel', 'Bray', 'F', 9000, 1, '2020-03-09'),
 (4, 'Priti', 'Agarwal', 'F', 10000, 2, '2020-03-01'),
 (6, 'Helly', 'Raval', 'F', 8000, 1, '2020-06-19'),
 (9, 'Cristina', 'Rel', 'F', 15000, 4, '2019-09-22')]

In [47]:
df[df.gender=='F']

ID first_name last_name gender  salary  level date_of_joining
1   2      Julie    Miller      F   12000      2      2020-01-14
2   3     Rachel      Bray      F    9000      1      2020-09-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
5   6      Helly     Raval      F    8000      1      2020-06-19
8   9   Cristina       Rel      F   15000      4      2019-09-22

In [49]:
%%sql
select ID, first_name, last_name from employee;

 * sqlite://
Done.


[(1, 'Peter', 'Sanders'),
 (2, 'Julie', 'Miller'),
 (3, 'Rachel', 'Bray'),
 (4, 'Priti', 'Agarwal'),
 (5, 'David', 'Cox'),
 (6, 'Helly', 'Raval'),
 (7, 'John', 'Frank'),
 (8, 'Mark', 'Franklin'),
 (9, 'Cristina', 'Rel'),
 (10, 'Brock', 'Murray')]

In [50]:
df[['ID', 'first_name', 'last_name']]

ID first_name last_name
0   1      Peter   Sanders
1   2      Julie    Miller
2   3     Rachel      Bray
3   4      Priti   Agarwal
4   5      David       Cox
5   6      Helly     Raval
6   7       John     Frank
7   8       Mark  Franklin
8   9   Cristina       Rel
9  10      Brock    Murray

In [53]:
%%sql
select * from employee order by salary desc;

 * sqlite://
Done.


[(9, 'Cristina', 'Rel', 'F', 15000, 4, '2019-09-22'),
 (8, 'Mark', 'Franklin', 'M', 13500, 3, '2019-11-12'),
 (7, 'John', 'Frank', 'M', 13000, 3, '2019-11-12'),
 (2, 'Julie', 'Miller', 'F', 12000, 2, '2020-01-14'),
 (10, 'Brock', 'Murray', 'M', 11000, 2, ' 2020-02-13'),
 (1, 'Peter', 'Sanders', 'M', 10000, 2, '2020-03-10'),
 (4, 'Priti', 'Agarwal', 'F', 10000, 2, '2020-03-01'),
 (3, 'Rachel', 'Bray', 'F', 9000, 1, '2020-03-09'),
 (6, 'Helly', 'Raval', 'F', 8000, 1, '2020-06-19'),
 (5, 'David', 'Cox', 'M', 5000, 1, '2020-05-28')]

In [54]:
df

ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2      2020-10-03
1   2      Julie    Miller      F   12000      2      2020-01-14
2   3     Rachel      Bray      F    9000      1      2020-09-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
4   5      David       Cox      M    5000      1      2020-05-28
5   6      Helly     Raval      F    8000      1      2020-06-19
6   7       John     Frank      M   13000      3      2019-12-11
7   8       Mark  Franklin      M   13500      3      2019-12-11
8   9   Cristina       Rel      F   15000      4      2019-09-22
9  10      Brock    Murray      M   11000      2      2020-02-13

In [57]:
df.sort_values(by='salary', ascending=False)

ID first_name last_name gender  salary  level date_of_joining
8   9   Cristina       Rel      F   15000      4      2019-09-22
7   8       Mark  Franklin      M   13500      3      2019-12-11
6   7       John     Frank      M   13000      3      2019-12-11
1   2      Julie    Miller      F   12000      2      2020-01-14
9  10      Brock    Murray      M   11000      2      2020-02-13
0   1      Peter   Sanders      M   10000      2      2020-10-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
2   3     Rachel      Bray      F    9000      1      2020-09-03
5   6      Helly     Raval      F    8000      1      2020-06-19
4   5      David       Cox      M    5000      1      2020-05-28

In [69]:
%%sql
select level, round(avg(salary),2) as average_salary, count(*) as count
from employee 
group by level;

 * sqlite://
Done.


[(1, 7333.33, 3), (2, 10750.0, 4), (3, 13250.0, 2), (4, 15000.0, 1)]

In [77]:
df.groupby('level').agg({'salary':'mean', 'ID':'size'})

salary  ID
level                  
1       7333.333333   3
2      10750.000000   4
3      13250.000000   2
4      15000.000000   1

In [73]:
df

ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2      2020-10-03
1   2      Julie    Miller      F   12000      2      2020-01-14
2   3     Rachel      Bray      F    9000      1      2020-09-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
4   5      David       Cox      M    5000      1      2020-05-28
5   6      Helly     Raval      F    8000      1      2020-06-19
6   7       John     Frank      M   13000      3      2019-12-11
7   8       Mark  Franklin      M   13500      3      2019-12-11
8   9   Cristina       Rel      F   15000      4      2019-09-22
9  10      Brock    Murray      M   11000      2      2020-02-13

In [81]:
%%sql
select distinct level from employee;

 * sqlite://
Done.


[(2,), (1,), (3,), (4,)]

In [85]:
%%sql
select count(distinct level) as count1 from employee;

 * sqlite://
Done.


[(4,)]

In [88]:
df.level.unique()

array([2, 1, 3, 4], dtype=int64)

In [94]:
df['level'].nunique()

4

In [95]:
df

ID first_name last_name gender  salary  level date_of_joining
0   1      Peter   Sanders      M   10000      2      2020-10-03
1   2      Julie    Miller      F   12000      2      2020-01-14
2   3     Rachel      Bray      F    9000      1      2020-09-03
3   4      Priti   Agarwal      F   10000      2      2020-01-03
4   5      David       Cox      M    5000      1      2020-05-28
5   6      Helly     Raval      F    8000      1      2020-06-19
6   7       John     Frank      M   13000      3      2019-12-11
7   8       Mark  Franklin      M   13500      3      2019-12-11
8   9   Cristina       Rel      F   15000      4      2019-09-22
9  10      Brock    Murray      M   11000      2      2020-02-13

In [96]:
df.shape

(10, 7)

In [99]:
%%sql 
select count(*) as employee_count from employee;

 * sqlite://
Done.


[(10,)]

In [100]:
! pip install pandas

In [101]:
import pandas as pd

In [102]:
book_title = ['C++', 'Java', 'Python', 'JavaScript']

In [104]:
book_title  = pd.Series(book_title)

In [105]:
book_title 

0           C++
1          Java
2        Python
3    JavaScript
dtype: object

In [106]:
type(book_title)

pandas.core.series.Series

In [107]:
book_title[2]

'Python'

In [108]:
book_title

0           C++
1          Java
2        Python
3    JavaScript
dtype: object

In [110]:
book_title.index = ['a', 'b', 'c', 'd']

In [111]:
book_title

a           C++
b          Java
c        Python
d    JavaScript
dtype: object

In [112]:
book_title['c']

'Python'

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
arr = np.random.randint(10,100,size = (6,4))

In [7]:
arr

array([[91, 24, 44, 31],
       [21, 35, 18, 56],
       [32, 77, 44, 24],
       [49, 67, 99, 88],
       [52, 13, 52, 15],
       [45, 69, 23, 19]])

In [9]:
df = pd.DataFrame(arr)  

In [11]:
type(df)

pandas.core.frame.DataFrame

In [14]:
type(df[2])

pandas.core.series.Series

In [16]:
type(df[0])

pandas.core.series.Series

In [20]:
df.columns = ["A", "B", "C", "D"]

In [21]:
df

A   B   C   D
0  91  24  44  31
1  21  35  18  56
2  32  77  44  24
3  49  67  99  88
4  52  13  52  15
5  45  69  23  19

In [23]:
df['D']

0    31
1    56
2    24
3    88
4    15
5    19
Name: D, dtype: int32

In [24]:
df.shape

(6, 4)

In [27]:
df.head(3)

A   B   C   D
0  91  24  44  31
1  21  35  18  56
2  32  77  44  24

In [29]:
df.tail(2)

A   B   C   D
4  52  13  52  15
5  45  69  23  19

In [30]:
df['C']

0    44
1    18
2    44
3    99
4    52
5    23
Name: C, dtype: int32

In [33]:
df[['C', 'D']]

C   D
0  44  31
1  18  56
2  44  24
3  99  88
4  52  15
5  23  19

In [36]:
df[['B', 'D', 'A']]

B   D   A
0  24  31  91
1  35  56  21
2  77  24  32
3  67  88  49
4  13  15  52
5  69  19  45

In [38]:
df['A+B'] = df['A'] + df['B']

In [39]:
df

A   B   C   D  A+B
0  91  24  44  31  115
1  21  35  18  56   56
2  32  77  44  24  109
3  49  67  99  88  116
4  52  13  52  15   65
5  45  69  23  19  114

In [41]:
df['A-B'] = df['A'] * df['B']

In [42]:
df

A   B   C   D  A+B   A-B
0  91  24  44  31  115  2184
1  21  35  18  56   56   735
2  32  77  44  24  109  2464
3  49  67  99  88  116  3283
4  52  13  52  15   65   676
5  45  69  23  19  114  3105

In [45]:
df.drop(columns='A-B', inplace=True)

In [46]:
df

A   B   C   D  A+B
0  91  24  44  31  115
1  21  35  18  56   56
2  32  77  44  24  109
3  49  67  99  88  116
4  52  13  52  15   65
5  45  69  23  19  114

In [50]:
r = "p q r r t u".split()

In [51]:
df.index = r

In [52]:
df

A   B   C   D  A+B
p  91  24  44  31  115
q  21  35  18  56   56
r  32  77  44  24  109
r  49  67  99  88  116
t  52  13  52  15   65
u  45  69  23  19  114

In [55]:
df.loc['p']

A       91
B       24
C       44
D       31
A+B    115
Name: p, dtype: int32

In [56]:
df.loc['t']

A      52
B      13
C      52
D      15
A+B    65
Name: t, dtype: int32

In [57]:
df.iloc[0]

A       91
B       24
C       44
D       31
A+B    115
Name: p, dtype: int32

In [58]:
df.iloc[4]

A      52
B      13
C      52
D      15
A+B    65
Name: t, dtype: int32

In [59]:
df.iloc[5]

A       45
B       69
C       23
D       19
A+B    114
Name: u, dtype: int32

In [60]:
df

A   B   C   D  A+B
p  91  24  44  31  115
q  21  35  18  56   56
r  32  77  44  24  109
r  49  67  99  88  116
t  52  13  52  15   65
u  45  69  23  19  114

In [61]:
df.iloc[1:4]

A   B   C   D  A+B
q  21  35  18  56   56
r  32  77  44  24  109
r  49  67  99  88  116

In [65]:
df.iloc[2:5][['A','B']]

A   B
r  32  77
r  49  67
t  52  13

In [70]:
df.iloc[-2:][['D', 'A+B']]

D  A+B
t  15   65
u  19  114

In [75]:
df.iloc[-2:,-2:]

D  A+B
t  15   65
u  19  114

In [80]:
df.iloc[4:, -2:]

D  A+B
t  15   65
u  19  114

In [81]:
df

A   B   C   D  A+B
p  91  24  44  31  115
q  21  35  18  56   56
r  32  77  44  24  109
r  49  67  99  88  116
t  52  13  52  15   65
u  45  69  23  19  114

In [83]:
mask = df>30

In [84]:
mask

A      B      C      D   A+B
p   True  False   True   True  True
q  False   True  False   True  True
r   True   True   True  False  True
r   True   True   True   True  True
t   True  False   True  False  True
u   True   True  False  False  True

In [85]:
df[mask]

A     B     C     D  A+B
p  91.0   NaN  44.0  31.0  115
q   NaN  35.0   NaN  56.0   56
r  32.0  77.0  44.0   NaN  109
r  49.0  67.0  99.0  88.0  116
t  52.0   NaN  52.0   NaN   65
u  45.0  69.0   NaN   NaN  114

In [88]:
df[df>30]

A     B     C     D  A+B
p  91.0   NaN  44.0  31.0  115
q   NaN  35.0   NaN  56.0   56
r  32.0  77.0  44.0   NaN  109
r  49.0  67.0  99.0  88.0  116
t  52.0   NaN  52.0   NaN   65
u  45.0  69.0   NaN   NaN  114

In [92]:
df[df.B>40]

A   B   C   D  A+B
r  32  77  44  24  109
r  49  67  99  88  116
u  45  69  23  19  114

In [98]:
df[df['B']>40][['C', 'D']]

C   D
r  44  24
r  99  88
u  23  19

In [100]:
df.A>40


p     True
q    False
r    False
r     True
t     True
u     True
Name: A, dtype: bool

In [102]:
df.D<50

p     True
q    False
r     True
r    False
t     True
u     True
Name: D, dtype: bool

In [108]:
df[(df['A']>40) & (df['D']<50)]

A   B   C   D  A+B
p  91  24  44  31  115
t  52  13  52  15   65
u  45  69  23  19  114

In [109]:
df

A   B   C   D  A+B
p  91  24  44  31  115
q  21  35  18  56   56
r  32  77  44  24  109
r  49  67  99  88  116
t  52  13  52  15   65
u  45  69  23  19  114

In [113]:
again_arr = df.values

In [111]:
df.columns

Index(['A', 'B', 'C', 'D', 'A+B'], dtype='object')

In [112]:
df.index

Index(['p', 'q', 'r', 'r', 't', 'u'], dtype='object')

In [114]:
again_arr

array([[ 91,  24,  44,  31, 115],
       [ 21,  35,  18,  56,  56],
       [ 32,  77,  44,  24, 109],
       [ 49,  67,  99,  88, 116],
       [ 52,  13,  52,  15,  65],
       [ 45,  69,  23,  19, 114]])

In [117]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

08-10-2022  12:25    <DIR>          .
08-10-2022  12:25    <DIR>          ..
07-10-2022  21:22    <DIR>          .ipynb_checkpoints
17-09-2022  13:06    <DIR>          __pycache__
16-09-2022  19:48         7,070,153 100-Business-English-Expressions.pdf
23-09-2022  08:41         1,139,062 101-Essays-That-Will-Change-The-Way-You-Think_.pdf
16-06-2022  12:41           885,091 1655188476743.pdf
16-06-2022  12:41           821,305 1655303783088.pdf
16-06-2022  12:42           805,584 1655361164152.pdf
24-06-2022  11:57         1,554,236 1655729738530.pdf
22-06-2022  11:00         2,858,697 1655808683836.pdf
22-06-2022  10:01           474,528 1655817362570.pdf
31-07-2022  23:27           194,662 1659268223394.pdf
01-08-2022  12:03           202,563 1659327300591.pdf
19-08-2022  11:56            95,777 1660554784534.pdf
31-08-2022  14:56            76,256 1660633425891.pdf
20-08-2022  13:03  

In [1]:
#import seaborn as sns
import pandas as pd
import numpy as np

In [114]:
df  = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
df.shape

(150, 5)

In [7]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [10]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [11]:
df.info()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [12]:
df.describe()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [13]:
import numpy as np
print(np.__version__)

1.23.3


In [16]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [17]:
df.species.nunique()

3

In [21]:
df[df.species == 'versicolor'].shape

(50, 5)

In [24]:
df.species.value_counts()['virginica']

50

In [27]:
df['sepal_length'].mean()

5.843333333333335

In [29]:
df.petal_width.max()

2.5

In [30]:
df.petal_width.min()

0.1

In [32]:
df.petal_width.sum()

179.8

In [33]:
df.petal_width

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [36]:
df.sort_values(by=["sepal_length",'sepal_width'])

sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [39]:
df.species.apply(len)

0      6
1      6
2      6
3      6
4      6
      ..
145    9
146    9
147    9
148    9
149    9
Name: species, Length: 150, dtype: int64

In [40]:
len('setosa')

6

In [41]:
len('virginica')

9

In [43]:
df.apply(lambda x:x+x)

sepal_length  sepal_width  petal_length  petal_width             species
0            10.2          7.0           2.8          0.4        setosasetosa
1             9.8          6.0           2.8          0.4        setosasetosa
2             9.4          6.4           2.6          0.4        setosasetosa
3             9.2          6.2           3.0          0.4        setosasetosa
4            10.0          7.2           2.8          0.4        setosasetosa
..            ...          ...           ...          ...                 ...
145          13.4          6.0          10.4          4.6  virginicavirginica
146          12.6          5.0          10.0          3.8  virginicavirginica
147          13.0          6.0          10.4          4.0  virginicavirginica
148          12.4          6.8          10.8          4.6  virginicavirginica
149          11.8          6.0          10.2          3.6  virginicavirginica

[150 rows x 5 columns]

In [50]:
df.aggregate('min')

sepal_length       4.3
sepal_width          2
petal_length         1
petal_width        0.1
species         setosa
dtype: object

In [51]:
df.aggregate(['min', 'max', 'mean', 'median'])

sepal_length  sepal_width  petal_length  petal_width    species
min         4.300000        2.000      1.000000     0.100000     setosa
max         7.900000        4.400      6.900000     2.500000  virginica
mean        5.843333        3.054      3.758667     1.198667        NaN
median      5.800000        3.000      4.350000     1.300000        NaN

In [53]:
group = df.groupby('species')

In [54]:
group.max()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [55]:
group.max()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [56]:
group.median()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [57]:
group.mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [65]:
(df[df.species == 'setosa'].sepal_length).mean()

5.005999999999999

In [66]:
group.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [67]:
group.sum()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [69]:
group.describe().T

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [70]:
import warnings
warnings.filterwarnings('ignore')

In [142]:
nan_idx

array([ 54, 147, 123,   9, 102, 129,   9,  89,  66, 126, 139,  74,  53,
       118, 147, 120, 132,  13,  49, 129])

In [115]:
nan_idx = np.random.randint(0,150,20)

In [116]:
df['sepal_length'][nan_idx] = np.nan

In [117]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           NaN          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [98]:
df.petal_width.idx1 = np.nan

In [124]:
idx1 = np.random.randint(0,150,15)

In [119]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           NaN          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [127]:
df.petal_width[139]

2.1

In [125]:
idx1

array([104,   0, 109,  57,  11,  20,  12,  91,  77,  49,  18, 149,  29,
       128, 108])

In [126]:
df['petal_width'][idx1] = np.nan

In [128]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          NaN     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           NaN          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [129]:
df.isna().sum()

sepal_length    17
sepal_width      0
petal_length     0
petal_width     30
species          0
dtype: int64

In [130]:
df.shape

(150, 5)

In [131]:
df.shape

(150, 5)

In [140]:
df['sepal_length'].fillna(value=round(df['sepal_length'].mean(),2), inplace=True)

In [138]:
round(df['sepal_length'].mean(),2)

5.8

In [141]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          NaN     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           5.8          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [144]:
df.isna().sum()

sepal_length     0
sepal_width      0
petal_length     0
petal_width     30
species          0
dtype: int64

In [147]:
df['petal_width'].fillna(value=round(df['petal_width'].mean(),2), inplace=True)

In [148]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4         1.22     setosa
1             4.9          3.0           1.4         0.20     setosa
2             4.7          3.2           1.3         0.20     setosa
3             4.6          3.1           1.5         0.20     setosa
4             5.0          3.6           1.4         0.20     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2         2.30  virginica
146           6.3          2.5           5.0         1.90  virginica
147           5.8          3.0           5.2         2.00  virginica
148           6.2          3.4           5.4         2.30  virginica
149           5.9          3.0           5.1         1.22  virginica

[150 rows x 5 columns]

In [150]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [155]:
new_df  = pd.DataFrame(np.random.randint(0,7,size = (10,4)))

In [156]:
new_df

0  1  2  3
0  6  6  3  3
1  4  5  2  0
2  2  3  5  5
3  6  1  5  2
4  5  1  2  0
5  2  2  3  1
6  3  6  6  6
7  3  2  3  2
8  1  3  5  3
9  5  1  2  1

In [160]:
new_df['species'] = 'new-species'

In [161]:
new_df

0  1  2  3      species
0  6  6  3  3  new-species
1  4  5  2  0  new-species
2  2  3  5  5  new-species
3  6  1  5  2  new-species
4  5  1  2  0  new-species
5  2  2  3  1  new-species
6  3  6  6  6  new-species
7  3  2  3  2  new-species
8  1  3  5  3  new-species
9  5  1  2  1  new-species

In [162]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [165]:
new_df.columns = df.columns

In [166]:
new_df

sepal_length  sepal_width  petal_length  petal_width      species
0             6            6             3            3  new-species
1             4            5             2            0  new-species
2             2            3             5            5  new-species
3             6            1             5            2  new-species
4             5            1             2            0  new-species
5             2            2             3            1  new-species
6             3            6             6            6  new-species
7             3            2             3            2  new-species
8             1            3             5            3  new-species
9             5            1             2            1  new-species

In [168]:
df1 = pd.concat((df,new_df))

In [170]:
df1.shape

(160, 5)

In [175]:
df2 = pd.DataFrame({"s_name":['Mohit', 'Jatin', 'Prateek', 'Mohit'],
             "CGPA":[ 2 , 4, 5, 3]})

In [176]:
df3 = pd.DataFrame({'T_Name' : ['Mohit', 'Jatin', 'Prateek', 'Mohit'],
                    'CGPA' :  [ 3 , 6, 8, 9]})

In [178]:
df2.merge(df3, on = 'CGPA')

s_name  CGPA T_Name
0  Mohit     3  Mohit

In [180]:
df2.merge(df3, how='left')

s_name  CGPA T_Name
0    Mohit     2    NaN
1    Jatin     4    NaN
2  Prateek     5    NaN
3    Mohit     3  Mohit

In [182]:
df2.merge(df3, how='right')

s_name  CGPA   T_Name
0  Mohit     3    Mohit
1    NaN     6    Jatin
2    NaN     8  Prateek
3    NaN     9    Mohit

In [184]:
df2.merge(df3, how='outer')

s_name  CGPA   T_Name
0    Mohit     2      NaN
1    Jatin     4      NaN
2  Prateek     5      NaN
3    Mohit     3    Mohit
4      NaN     6    Jatin
5      NaN     8  Prateek
6      NaN     9    Mohit

In [186]:
df1

sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4         1.22       setosa
1            4.9          3.0           1.4         0.20       setosa
2            4.7          3.2           1.3         0.20       setosa
3            4.6          3.1           1.5         0.20       setosa
4            5.0          3.6           1.4         0.20       setosa
..           ...          ...           ...          ...          ...
5            2.0          2.0           3.0         1.00  new-species
6            3.0          6.0           6.0         6.00  new-species
7            3.0          2.0           3.0         2.00  new-species
8            1.0          3.0           5.0         3.00  new-species
9            5.0          1.0           2.0         1.00  new-species

[160 rows x 5 columns]

In [188]:
df1.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [190]:
df1.to_csv('mypandas152.csv', index= False)

In [192]:
modified_iris  = pd.read_csv('mypandas152.csv')

In [193]:
modified_iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4         1.22  setosa
1           4.9          3.0           1.4         0.20  setosa
2           4.7          3.2           1.3         0.20  setosa
3           4.6          3.1           1.5         0.20  setosa
4           5.0          3.6           1.4         0.20  setosa

In [195]:
df1.to_excel('thisisexcelfile.xlsx', sheet_name='ironmanfile')

In [196]:
!pip install numpy

In [197]:
import numpy as np

In [198]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [202]:
%timeit [i**2 for i in lst]

1.92 µs ± 32.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [204]:
arr = np.array(lst)

In [208]:
%timeit arr**2

489 ns ± 15.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [209]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [212]:
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [214]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [215]:
l = [1,5,8,9]

In [217]:
np_arr  = np.array(l)

In [218]:
np_arr

array([1, 5, 8, 9])

In [219]:
type(np_arr)

numpy.ndarray

In [220]:
np_arr.ndim

1

In [221]:
np_arr.shape

(4,)

In [224]:
list(range(0,15,3))

[0, 3, 6, 9, 12]

In [227]:
new_arr  = np.arange(3,11,2)

In [228]:
new_arr

array([3, 5, 7, 9])

In [230]:
lst_2d = [[1,2,3], [4,5,6], [7,8,9]]

In [231]:
type(lst_2d)

list

In [233]:
a1 =np.array(lst_2d)

In [235]:
a1.shape

(3, 3)

In [236]:
a1.ndim

2

In [248]:
z = np.zeros((5,5), dtype = np.int32)

In [245]:
o = np.ones((9,9), )

In [250]:
z.dtype

dtype('int32')

In [249]:
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [251]:
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [252]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [253]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [255]:
np.diag((6,6))

array([[6, 0],
       [0, 6]])

In [256]:
np.diag([1,2,25,36,100])

array([[  1,   0,   0,   0,   0],
       [  0,   2,   0,   0,   0],
       [  0,   0,  25,   0,   0],
       [  0,   0,   0,  36,   0],
       [  0,   0,   0,   0, 100]])

In [260]:
arr = np.random.randint(10,100, (5,4))

In [262]:
arr.shape

(5, 4)

In [264]:
arr[0]

array([39, 70, 56, 44])

In [265]:
arr[2]

array([75, 14, 20, 84])

In [266]:
arr

array([[39, 70, 56, 44],
       [17, 93, 68, 56],
       [75, 14, 20, 84],
       [56, 34, 24, 51],
       [59, 72, 23, 96]])

In [267]:
arr[-2]

array([56, 34, 24, 51])

In [269]:
arr[0,0]

39

In [274]:
arr[4,3]

96

In [275]:
arr

array([[39, 70, 56, 44],
       [17, 93, 68, 56],
       [75, 14, 20, 84],
       [56, 34, 24, 51],
       [59, 72, 23, 96]])

In [280]:
arr[2:,1:]

array([[14, 20, 84],
       [34, 24, 51],
       [72, 23, 96]])

In [284]:
arr[:,-1]

array([44, 56, 84, 51, 96])

In [289]:
arr[0,1] = 145

In [290]:
arr

array([[ 39, 145,  56,  44],
       [ 17,  93,  68,  56],
       [ 75,  14,  20,  84],
       [ 56,  34,  24,  51],
       [ 59,  72,  23,  96]])

In [295]:
mask = arr>10

In [296]:
mask.sum()

20

In [297]:
np.sum(mask)

20

In [300]:
arr[arr>10]

array([ 39, 145,  56,  44,  17,  93,  68,  56,  75,  14,  20,  84,  56,
        34,  24,  51,  59,  72,  23,  96])

In [306]:
arr[2:,2:] = 0

In [307]:
arr

array([[ 39, 145,  56,  44],
       [ 17,  93,  68,  56],
       [ 75,  14,   0,   0],
       [ 56,  34,   0,   0],
       [ 59,  72,   0,   0]])

In [309]:
a = np.array([10,20,30.,40])

In [311]:
b = np.arange(1,5)

In [312]:
a

array([10., 20., 30., 40.])

In [313]:
b

array([1, 2, 3, 4])

In [314]:
a+b

array([11., 22., 33., 44.])

In [315]:
a-b

array([ 9., 18., 27., 36.])

In [316]:
a*b

array([ 10.,  40.,  90., 160.])

In [317]:
b**2

array([ 1,  4,  9, 16])

In [319]:
a>15

array([False,  True,  True,  True])

In [320]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [321]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

In [322]:
np.tanh(a)

array([1., 1., 1., 1.])

In [325]:
a = np.random.randint(0,5,(3,4))

In [328]:
b = np.random.randint(0,5,(4,2))

In [329]:
a@b

array([[23,  6],
       [39, 16],
       [15,  2]])

In [ ]:
#a*b

In [331]:
np.dot(a,b)

array([[23,  6],
       [39, 16],
       [15,  2]])

In [333]:
a = np.arange(0,24)

In [334]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [336]:
a = a.reshape(6,4)

In [337]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [338]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [346]:
np.sum(a, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [348]:
np.min(a, axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [341]:
np.max(a)

23

In [350]:
np.mean(a, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [352]:
np.std(a, axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399])

In [344]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [353]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [354]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [355]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [357]:
a.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [358]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [359]:
a.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [360]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [361]:
np.transpose(a)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [364]:
a = np.random.randint(0,10,(2,2))

In [367]:
b = np.random.randint(0,10, (2,2))

In [368]:
a

array([[5, 7],
       [1, 1]])

In [369]:
b

array([[1, 6],
       [4, 9]])

In [371]:
np.vstack((a,b))

array([[5, 7],
       [1, 1],
       [1, 6],
       [4, 9]])

In [372]:
np.hstack((a,b))

array([[5, 7, 1, 6],
       [1, 1, 4, 9]])

In [375]:
a = np.random.randint(0,10,(3,3))

In [380]:
b = np.array([[1,2,3]])

In [381]:
a

array([[6, 9, 7],
       [0, 8, 8],
       [2, 3, 6]])

In [382]:
b

array([[1, 2, 3]])

In [383]:
a.shape

(3, 3)

In [384]:
b.shape

(1, 3)

In [385]:
a+b

array([[ 7, 11, 10],
       [ 1, 10, 11],
       [ 3,  5,  9]])

In [388]:
a + b.T

array([[ 7, 10,  8],
       [ 2, 10, 10],
       [ 5,  6,  9]])

In [389]:
 a

array([[6, 9, 7],
       [0, 8, 8],
       [2, 3, 6]])

In [390]:
a+4

array([[10, 13, 11],
       [ 4, 12, 12],
       [ 6,  7, 10]])

In [392]:
p1 = np.array([1,2,4,7,-2,9,6,0])

In [396]:
p2 =  np.array([5,5,8,2,-9,2,1,6])

In [397]:
s = 0
for i in range(8):
    s+=(p2[i]-p1[i])**2

In [398]:
s

225

In [399]:
np.sqrt(s)

15.0

In [400]:
s**0.5

15.0

In [411]:
def distance(p1,p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [412]:
distance(p1,p2)

15.0