In [6]:
!pip install numpy



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [8]:
lst = [5,7,9,10,15,16,17]

In [9]:
s = []
for i in lst:
    s.append(i+1)

In [10]:
s


[6, 8, 10, 11, 16, 17, 18]

In [13]:
%timeit [i**2 for i in lst]

1.42 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
arr = np.array(lst)

In [16]:
arr+1

array([ 6,  8, 10, 11, 16, 17, 18])

In [18]:
%timeit (arr**2)

487 ns ± 77.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
lst + 5

TypeError: can only concatenate list (not "int") to list

In [20]:
lst + [5]

[5, 7, 9, 10, 15, 16, 17, 5]

In [21]:
arr + 5

array([10, 12, 14, 15, 20, 21, 22])

In [23]:
set(range(1,10))

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [26]:
arr1 = np.arange(1,31,5)

In [27]:
lst = [1,5,8,9,10,15,16]

In [29]:
arr2 = np.array(lst)

In [30]:
arr2.shape

(7,)

In [31]:
arr2.ndim

1

In [32]:
type(arr2)

numpy.ndarray

In [34]:
tuple(range(1,21))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [36]:
new_arr = np.arange(1,21,3)

In [37]:
new_arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [39]:
new_arr3 = np.arange(3,21,3)

In [40]:
new_arr3

array([ 3,  6,  9, 12, 15, 18])

In [41]:
lst_2d = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

In [42]:
lst_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [44]:
arr4 = np.array(lst_2d)

In [45]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
arr4.shape

(4, 3)

In [47]:
arr4.ndim

2

In [48]:
arr4.nbytes

48

In [49]:
type(arr4)

numpy.ndarray

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.diag([8])

array([[8]])

In [61]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [64]:
np.diag((7,5,3))

array([[7, 0, 0],
       [0, 5, 0],
       [0, 0, 3]])

In [65]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.random.randint(10,100)

76

In [69]:
new_arr = np.random.randint(1,100, (8,6))

In [70]:
new_arr.shape

(8, 6)

In [71]:
type(new_arr)

numpy.ndarray

In [72]:
print(new_arr)

[[ 7 27 29 66 97  4]
 [65 40 13  4 29 14]
 [58 75 17 20 81 44]
 [44 98 85 89 27 93]
 [76 12 11 49 30 80]
 [32 73 34 64 58 52]
 [57 39 37 57 31 62]
 [97 96 77 14 16 45]]


In [73]:
new_arr[0]

array([ 7, 27, 29, 66, 97,  4])

In [74]:
new_arr[1]

array([65, 40, 13,  4, 29, 14])

In [75]:
new_arr[5]

array([32, 73, 34, 64, 58, 52])

In [76]:
new_arr[-1]

array([97, 96, 77, 14, 16, 45])

In [77]:
new_arr[-2]

array([57, 39, 37, 57, 31, 62])

In [78]:
new_arr

array([[ 7, 27, 29, 66, 97,  4],
       [65, 40, 13,  4, 29, 14],
       [58, 75, 17, 20, 81, 44],
       [44, 98, 85, 89, 27, 93],
       [76, 12, 11, 49, 30, 80],
       [32, 73, 34, 64, 58, 52],
       [57, 39, 37, 57, 31, 62],
       [97, 96, 77, 14, 16, 45]])

In [79]:
new_arr[:,0]

array([ 7, 65, 58, 44, 76, 32, 57, 97])

In [80]:
new_arr[:,1]

array([27, 40, 75, 98, 12, 73, 39, 96])

In [81]:
new_arr[:, -1]

array([ 4, 14, 44, 93, 80, 52, 62, 45])

In [82]:
new_arr[:,-2]

array([97, 29, 81, 27, 30, 58, 31, 16])

In [83]:
new_arr


array([[ 7, 27, 29, 66, 97,  4],
       [65, 40, 13,  4, 29, 14],
       [58, 75, 17, 20, 81, 44],
       [44, 98, 85, 89, 27, 93],
       [76, 12, 11, 49, 30, 80],
       [32, 73, 34, 64, 58, 52],
       [57, 39, 37, 57, 31, 62],
       [97, 96, 77, 14, 16, 45]])

In [85]:
new_arr[0,0]

7

In [87]:
new_arr[3,2]

85

In [89]:
new_arr[-1,-1]

45

In [92]:
new_arr[4:, 3:]

array([[49, 30, 80],
       [64, 58, 52],
       [57, 31, 62],
       [14, 16, 45]])

In [93]:
new_arr[:,2]

array([29, 13, 17, 85, 11, 34, 37, 77])

In [94]:
new_arr[:,-1]

array([ 4, 14, 44, 93, 80, 52, 62, 45])

In [98]:
new_arr[0,0] = 0

In [99]:
new_arr

array([[ 0, 27, 29, 66, 97,  4],
       [65, 40, 13,  4, 29, 14],
       [58, 75, 17, 20, 81, 44],
       [44, 98, 85, 89, 27, 93],
       [76, 12, 11, 49, 30, 80],
       [32, 73, 34, 64, 58, 52],
       [57, 39, 37, 57, 31, 62],
       [97, 96, 77, 14, 16, 45]])

In [100]:
# masking

In [102]:
new_arr[new_arr>10]

array([27, 29, 66, 97, 65, 40, 13, 29, 14, 58, 75, 17, 20, 81, 44, 44, 98,
       85, 89, 27, 93, 76, 12, 11, 49, 30, 80, 32, 73, 34, 64, 58, 52, 57,
       39, 37, 57, 31, 62, 97, 96, 77, 14, 16, 45])

In [104]:
mask = new_arr>50

In [105]:
print(mask)

[[False False False  True  True False]
 [ True False False False False False]
 [ True  True False False  True False]
 [False  True  True  True False  True]
 [ True False False False False  True]
 [False  True False  True  True  True]
 [ True False False  True False  True]
 [ True  True  True False False False]]


In [107]:
np.sum(new_arr>50)

22

In [109]:
new_arr[new_arr>50]

array([66, 97, 65, 58, 75, 81, 98, 85, 89, 93, 76, 80, 73, 64, 58, 52, 57,
       57, 62, 97, 96, 77])

In [114]:
new_arr[-2:, -2:] = 0

In [115]:
new_arr

array([[ 0, 27, 29, 66, 97,  4],
       [65, 40, 13,  4, 29, 14],
       [58, 75, 17, 20, 81, 44],
       [44, 98, 85, 89, 27, 93],
       [76, 12, 11, 49, 30, 80],
       [32, 73, 34, 64, 58, 52],
       [57, 39, 37, 57,  0,  0],
       [97, 96, 77, 14,  0,  0]])

In [116]:
# Basic opeartions in array

In [117]:
a = np.array([10,20,30,40])

In [119]:
b = np.arange(1,5)

In [120]:
a

array([10, 20, 30, 40])

In [121]:

b

array([1, 2, 3, 4])

In [122]:
a+b

array([11, 22, 33, 44])

In [123]:
a-b

array([ 9, 18, 27, 36])

In [124]:
a*b

array([ 10,  40,  90, 160])

In [125]:
a/b

array([10., 10., 10., 10.])

In [126]:
a%b

array([0, 0, 0, 0])

In [127]:
b**2

array([ 1,  4,  9, 16])

In [129]:
np.sum(a>15)

3

In [130]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [131]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [132]:
A = np.random.randint(1,100,(4,3))

In [133]:
B  =np.random.randint(15,150,(3,5))

In [134]:
np.dot(A,B)

array([[15495, 16344, 16584, 12168, 12359],
       [15818, 15916, 17388, 12236, 12574],
       [22238, 20344, 21666, 14552, 16867],
       [ 8230,  6750,  7390,  4606,  6008]])

In [135]:
# More operations on Arrays

In [136]:
arr = np.arange(0,24)

In [137]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [139]:
A = arr.reshape(6,4)

In [140]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [141]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [143]:
np.sum(A)

276

In [144]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [145]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [146]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [147]:
np.mean(A)

11.5

In [148]:
np.mean(A, axis=0)

array([10., 11., 12., 13.])

In [149]:
np.mean(A, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [150]:
np.max(A)

23

In [151]:
np.max(A, axis=0)

array([20, 21, 22, 23])

In [152]:
np.min(A, axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [155]:
np.round(np.std(A), 2)

6.92

In [156]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [158]:
A = A.reshape(8,3)

In [159]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [160]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [161]:
A.T

array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23]])

In [162]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [163]:
np.transpose(A)

array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23]])

In [164]:
# staccking

In [166]:
d =np.random.randint(1,500,(3,3))

In [168]:
w = np.random.randint(500,2000,(3,3))

In [169]:
w

array([[1764, 1533, 1725],
       [1040,  822, 1979],
       [ 776,  617, 1023]])

In [170]:
d

array([[425, 322, 101],
       [310, 349, 321],
       [410,  55, 405]])

In [171]:
np.vstack((w,d))

array([[1764, 1533, 1725],
       [1040,  822, 1979],
       [ 776,  617, 1023],
       [ 425,  322,  101],
       [ 310,  349,  321],
       [ 410,   55,  405]])

In [172]:
np.hstack((d,w))

array([[ 425,  322,  101, 1764, 1533, 1725],
       [ 310,  349,  321, 1040,  822, 1979],
       [ 410,   55,  405,  776,  617, 1023]])

In [173]:
a = np.random.randint(1,10,(3,3))

In [174]:
b = np.array([1,2,3])

In [175]:
a

array([[7, 9, 7],
       [3, 1, 4],
       [7, 2, 5]])

In [176]:
b

array([1, 2, 3])

In [177]:
a + b

array([[ 8, 11, 10],
       [ 4,  3,  7],
       [ 8,  4,  8]])

In [178]:
a.T

array([[7, 3, 7],
       [9, 1, 2],
       [7, 4, 5]])

In [179]:
a + a.T

array([[14, 12, 14],
       [12,  2,  6],
       [14,  6, 10]])

In [180]:
a

array([[7, 9, 7],
       [3, 1, 4],
       [7, 2, 5]])

In [181]:
a + 8

array([[15, 17, 15],
       [11,  9, 12],
       [15, 10, 13]])

In [205]:
p1 = np.random.randint(1,100,(8))

In [206]:
p2 = np.array([5,5,8,2,-9,2,1,6])

In [207]:
def distance(p1,p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [208]:
distance(p1,p2)

129.73819792181484

In [192]:
p1

array([40, 14, 61, 83, 28, 93, 59, 81])

In [193]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [209]:
sum__ = 0
for i in range(len(p1)):
    sum__+=(p2[i]-p1[i])**2

In [210]:
sum__

16832

In [211]:
sum__**0.5

129.73819792181484

In [212]:
p1 = np.array([1,2, 4, 7, -2, 9, 6, 0])
p2 = np.array([5,5, 8, 2, -9, 2, 1, 6])

In [213]:
distance(p1,p2)

15.0

In [214]:
sum__ = 0
for i in range(len(p1)):
    sum__+=(p2[i]-p1[i])**2

In [215]:
sum__

225

In [216]:
sum__**0.5

15.0

In [217]:
# Pandas

In [218]:
!pip install pandas


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [219]:
import pandas as pd

In [220]:
lst = ['c', 'c++', 'python', 'java', 'HTML']

In [222]:
book_title = pd.Series(lst)

In [223]:
book_title

0         c
1       c++
2    python
3      java
4      HTML
dtype: object

In [224]:
type(book_title)

pandas.core.series.Series

In [225]:
book_title[0]

'c'

In [227]:
book_title[3]

'java'

In [228]:
book_title[1]

'c++'

In [231]:
book_title.index = ['a', 'b', 'c', 'd', 'e']

In [232]:
book_title

a         c
b       c++
c    python
d      java
e      HTML
dtype: object

In [234]:
book_title[2]

'python'

In [235]:
book_title['c']

'python'

In [236]:
import numpy as np

In [238]:
arr = np.random.randint(10,100, size = (8,6))

In [242]:
df = pd.DataFrame(data=arr)

In [243]:
df

0   1   2   3   4   5
0  64  44  51  97  14  74
1  27  58  16  56  81  18
2  71  84  65  77  66  73
3  22  69  46  32  82  82
4  72  86  99  77  26  69
5  35  47  21  28  27  93
6  11  25  53  71  56  21
7  57  75  19  52  63  28

In [244]:
type(df)

pandas.core.frame.DataFrame

In [246]:
df[0]

0    64
1    27
2    71
3    22
4    72
5    35
6    11
7    57
Name: 0, dtype: int32

In [248]:
df[2]

0    51
1    16
2    65
3    46
4    99
5    21
6    53
7    19
Name: 2, dtype: int32

In [252]:
type(df[5])

pandas.core.series.Series

In [255]:
df.columns = ['A','B', 'C', 'D', 'E','F']

In [256]:
df

A   B   C   D   E   F
0  64  44  51  97  14  74
1  27  58  16  56  81  18
2  71  84  65  77  66  73
3  22  69  46  32  82  82
4  72  86  99  77  26  69
5  35  47  21  28  27  93
6  11  25  53  71  56  21
7  57  75  19  52  63  28

In [257]:
df['A']

0    64
1    27
2    71
3    22
4    72
5    35
6    11
7    57
Name: A, dtype: int32

In [258]:
df['C']

0    51
1    16
2    65
3    46
4    99
5    21
6    53
7    19
Name: C, dtype: int32

In [259]:
df

A   B   C   D   E   F
0  64  44  51  97  14  74
1  27  58  16  56  81  18
2  71  84  65  77  66  73
3  22  69  46  32  82  82
4  72  86  99  77  26  69
5  35  47  21  28  27  93
6  11  25  53  71  56  21
7  57  75  19  52  63  28

In [260]:
df.shape

(8, 6)

In [262]:
df.head(3)

A   B   C   D   E   F
0  64  44  51  97  14  74
1  27  58  16  56  81  18
2  71  84  65  77  66  73

In [265]:
df.tail(2)

A   B   C   D   E   F
6  11  25  53  71  56  21
7  57  75  19  52  63  28

In [269]:
df.sample(3)

A   B   C   D   E   F
0  64  44  51  97  14  74
4  72  86  99  77  26  69
5  35  47  21  28  27  93

In [271]:
df['D']

0    97
1    56
2    77
3    32
4    77
5    28
6    71
7    52
Name: D, dtype: int32

In [275]:
df[['C', 'D']]

C   D
0  51  97
1  16  56
2  65  77
3  46  32
4  99  77
5  21  28
6  53  71
7  19  52

In [277]:
df[['D', 'A','B']]

D   A   B
0  97  64  44
1  56  27  58
2  77  71  84
3  32  22  69
4  77  72  86
5  28  35  47
6  71  11  25
7  52  57  75

In [279]:
df['A']

0    64
1    27
2    71
3    22
4    72
5    35
6    11
7    57
Name: A, dtype: int32

In [280]:
df['B']

0    44
1    58
2    84
3    69
4    86
5    47
6    25
7    75
Name: B, dtype: int32

In [282]:
df['A+B'] =  df['A'] + df['B']

In [283]:

df

A   B   C   D   E   F  A+B
0  64  44  51  97  14  74  108
1  27  58  16  56  81  18   85
2  71  84  65  77  66  73  155
3  22  69  46  32  82  82   91
4  72  86  99  77  26  69  158
5  35  47  21  28  27  93   82
6  11  25  53  71  56  21   36
7  57  75  19  52  63  28  132

In [286]:
df['A*B'] =df['A'] *  df['B']

In [287]:
df

A   B   C   D   E   F  A+B   A*B
0  64  44  51  97  14  74  108  2816
1  27  58  16  56  81  18   85  1566
2  71  84  65  77  66  73  155  5964
3  22  69  46  32  82  82   91  1518
4  72  86  99  77  26  69  158  6192
5  35  47  21  28  27  93   82  1645
6  11  25  53  71  56  21   36   275
7  57  75  19  52  63  28  132  4275

In [292]:
df.drop(labels='D', axis=1, inplace=True)

In [293]:
df

A   B   C   E   F  A+B   A*B
0  64  44  51  14  74  108  2816
1  27  58  16  81  18   85  1566
2  71  84  65  66  73  155  5964
3  22  69  46  82  82   91  1518
4  72  86  99  26  69  158  6192
5  35  47  21  27  93   82  1645
6  11  25  53  56  21   36   275
7  57  75  19  63  28  132  4275

In [298]:
df.drop(columns=['A+B', 'A*B'])

A   B   C   E   F
0  64  44  51  14  74
1  27  58  16  81  18
2  71  84  65  66  73
3  22  69  46  82  82
4  72  86  99  26  69
5  35  47  21  27  93
6  11  25  53  56  21
7  57  75  19  63  28

In [302]:
df.drop(index=[0,1])

A   B   C   E   F  A+B   A*B
2  71  84  65  66  73  155  5964
3  22  69  46  82  82   91  1518
4  72  86  99  26  69  158  6192
5  35  47  21  27  93   82  1645
6  11  25  53  56  21   36   275
7  57  75  19  63  28  132  4275

In [305]:
df.drop(labels=[0,1])

A   B   C   E   F  A+B   A*B
2  71  84  65  66  73  155  5964
3  22  69  46  82  82   91  1518
4  72  86  99  26  69  158  6192
5  35  47  21  27  93   82  1645
6  11  25  53  56  21   36   275
7  57  75  19  63  28  132  4275

In [308]:
df = df.drop(columns=['A+B', 'A*B'])

In [309]:
df

A   B   C   E   F
0  64  44  51  14  74
1  27  58  16  81  18
2  71  84  65  66  73
3  22  69  46  82  82
4  72  86  99  26  69
5  35  47  21  27  93
6  11  25  53  56  21
7  57  75  19  63  28

In [312]:
df.index = 'p q r s t u v w'.split()

In [313]:
df

A   B   C   E   F
p  64  44  51  14  74
q  27  58  16  81  18
r  71  84  65  66  73
s  22  69  46  82  82
t  72  86  99  26  69
u  35  47  21  27  93
v  11  25  53  56  21
w  57  75  19  63  28

In [315]:
df.loc['p']

A    64
B    44
C    51
E    14
F    74
Name: p, dtype: int32

In [318]:
df.iloc[0]

A    64
B    44
C    51
E    14
F    74
Name: p, dtype: int32

In [320]:
df.loc['q']

A    27
B    58
C    16
E    81
F    18
Name: q, dtype: int32

In [324]:
df.loc['s']

A    22
B    69
C    46
E    82
F    82
Name: s, dtype: int32

In [326]:
df.iloc[3]

A    22
B    69
C    46
E    82
F    82
Name: s, dtype: int32

In [328]:
df.loc['w']

A    57
B    75
C    19
E    63
F    28
Name: w, dtype: int32

In [329]:
df

A   B   C   E   F
p  64  44  51  14  74
q  27  58  16  81  18
r  71  84  65  66  73
s  22  69  46  82  82
t  72  86  99  26  69
u  35  47  21  27  93
v  11  25  53  56  21
w  57  75  19  63  28

In [330]:
df.iloc[-1]

A    57
B    75
C    19
E    63
F    28
Name: w, dtype: int32

In [333]:
df.iloc[5:, 2:]

C   E   F
u  21  27  93
v  53  56  21
w  19  63  28

In [339]:
df.iloc[-3:, -3:][['E', 'F']]

E   F
u  27  93
v  56  21
w  63  28

In [344]:
df.iloc[-2:][['A', 'B']]

A   B
v  11  25
w  57  75

In [348]:
df.iloc[-2:, -2:]

E   F
v  56  21
w  63  28

In [349]:
# Masking - Boolean masking

In [352]:
df[df>15]

A   B   C     E   F
p  64.0  44  51   NaN  74
q  27.0  58  16  81.0  18
r  71.0  84  65  66.0  73
s  22.0  69  46  82.0  82
t  72.0  86  99  26.0  69
u  35.0  47  21  27.0  93
v   NaN  25  53  56.0  21
w  57.0  75  19  63.0  28

In [355]:
df[df>30]

A     B     C     E     F
p  64.0  44.0  51.0   NaN  74.0
q   NaN  58.0   NaN  81.0   NaN
r  71.0  84.0  65.0  66.0  73.0
s   NaN  69.0  46.0  82.0  82.0
t  72.0  86.0  99.0   NaN  69.0
u  35.0  47.0   NaN   NaN  93.0
v   NaN   NaN  53.0  56.0   NaN
w  57.0  75.0   NaN  63.0   NaN

In [362]:
df[df['B']>40][['B', 'C']]

B   C
p  44  51
q  58  16
r  84  65
s  69  46
t  86  99
u  47  21
w  75  19

In [369]:
df[df['A']>40][['A','B']]

A   B
p  64  44
r  71  84
t  72  86
w  57  75

In [373]:
df['C']

p    51
q    16
r    65
s    46
t    99
u    21
v    53
w    19
Name: C, dtype: int32

In [377]:
df[df.C<50]

A   B   C   E   F
q  27  58  16  81  18
s  22  69  46  82  82
u  35  47  21  27  93
w  57  75  19  63  28

In [383]:
df[(df['A']>40) & (df['C']<50)]

A   B   C   E   F
w  57  75  19  63  28

In [381]:
df['C']<50

p    False
q     True
r    False
s     True
t    False
u     True
v    False
w     True
Name: C, dtype: bool

In [385]:
df.values

array([[64, 44, 51, 14, 74],
       [27, 58, 16, 81, 18],
       [71, 84, 65, 66, 73],
       [22, 69, 46, 82, 82],
       [72, 86, 99, 26, 69],
       [35, 47, 21, 27, 93],
       [11, 25, 53, 56, 21],
       [57, 75, 19, 63, 28]])

In [386]:
# iris data

In [389]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

14-09-2023  23:32    <DIR>          .
04-09-2023  00:15    <DIR>          ..
14-09-2023  21:43    <DIR>          .ipynb_checkpoints
02-11-2022  15:49           410,816 0211resume.pdf
03-09-2023  14:20            54,756 03_09_1_pm_Functions.ipynb
20-03-2023  16:51           118,844 04_06.ipynb
05-08-2023  17:33       144,122,096 05_08_1PM.zip
05-08-2023  17:32            28,266 05_08_firoj_tapan.ipynb
08-04-2023  17:46             6,413 08_04_2023_window functions__damini_04_06.sql
08-05-2023  17:43           453,229 08_05_power bi.pbix
08-11-2022  11:41           412,631 08novresume.pdf
09-04-2023  17:37             2,262 09_damini stored_processor.sql
08-10-2022  12:44               582 1.0.5
11-04-2023  14:25       279,467,547 10_04_2023.mp4
16-09-2022  19:48         7,070,153 100-Business-English-Expressions.pdf
23-09-2022  08:41         1,139,062 101-Essays-That-Will-Change-The-Way-

02-01-2023  15:48            28,209 dataset issue.png
13-09-2022  21:39        24,741,696 dataset.rar
27-04-2023  16:32    <DIR>          data-society-global-terrorism-data
31-03-2023  20:14           118,690 Dax 2.pbix
31-03-2023  18:08           430,086 DAX.pbix
11-10-2022  13:38         2,493,152 Day04-Docker-20221011T080805Z-001.zip
07-01-2023  13:33            31,303 ddddddWRrrrrrrr.png
05-08-2022  11:46         1,569,899 Deep learning (2).pdf
01-08-2022  14:05           378,488 Deep Learning.pdf
06-12-2022  14:50    <DIR>          Deployement
27-09-2022  18:35    <DIR>          Diabetes-prediction-project-main
27-09-2022  18:35         1,576,224 Diabetes-prediction-project-main.zip
27-09-2022  18:34           510,271 diabetes-prediction-rfc-model.pkl
16-07-2023  14:46           970,487 diamond price.pdf
08-01-2023  13:06           546,634 Dissertation.pptx
09-09-2022  21:49    <DIR>          Django-Socialauth-master
09-09-2022  21:49           146,954 Django-Socialauth-master.zip

In [392]:
df = pd.read_csv('./iris.csv')

In [393]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [394]:
type(df)

pandas.core.frame.DataFrame

In [395]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [396]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [397]:
df.shape

(150, 5)

In [398]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [399]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [400]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [402]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [403]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [404]:
df.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.054000      3.758667     1.198667     NaN
std         0.828066     0.433594      1.764420     0.763161     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [405]:
df.describe(include='object')

species
count      150
unique       3
top     setosa
freq        50

In [407]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [409]:
df.species.nunique()

3

In [413]:
df[df.species == 'versicolor'].shape

(50, 5)

In [417]:
df.species.value_counts()['setosa']

50

In [419]:
df.petal_length.min()

1.0

In [420]:
df.petal_width.sum()

179.8

In [421]:
df.sepal_length.max()

7.9

In [423]:
round(df.sepal_width.mean())

3

In [424]:
df['petal_width']

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [425]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [434]:
df.sort_values(by=['sepal_length','sepal_width'], ascending=[True, False])

sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [438]:
df = df.sort_values(by='petal_length', ascending=False)

In [440]:
df.sort_index()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [441]:
import pandas as pd

In [442]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')

In [446]:
df.sepal_length = df.sepal_length.apply(lambda x:round(x))

In [447]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0               5          3.5           1.4          0.2     setosa
1               5          3.0           1.4          0.2     setosa
2               5          3.2           1.3          0.2     setosa
3               5          3.1           1.5          0.2     setosa
4               5          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145             7          3.0           5.2          2.3  virginica
146             6          2.5           5.0          1.9  virginica
147             6          3.0           5.2          2.0  virginica
148             6          3.4           5.4          2.3  virginica
149             6          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [450]:
df.species.apply(len)

0      6
1      6
2      6
3      6
4      6
      ..
145    9
146    9
147    9
148    9
149    9
Name: species, Length: 150, dtype: int64

In [452]:
df.apply(lambda x:x+x)

sepal_length  sepal_width  petal_length  petal_width             species
0              10          7.0           2.8          0.4        setosasetosa
1              10          6.0           2.8          0.4        setosasetosa
2              10          6.4           2.6          0.4        setosasetosa
3              10          6.2           3.0          0.4        setosasetosa
4              10          7.2           2.8          0.4        setosasetosa
..            ...          ...           ...          ...                 ...
145            14          6.0          10.4          4.6  virginicavirginica
146            12          5.0          10.0          3.8  virginicavirginica
147            12          6.0          10.4          4.0  virginicavirginica
148            12          6.8          10.8          4.6  virginicavirginica
149            12          6.0          10.2          3.6  virginicavirginica

[150 rows x 5 columns]

In [453]:
# Grouping data together

In [454]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0               5          3.5           1.4          0.2     setosa
1               5          3.0           1.4          0.2     setosa
2               5          3.2           1.3          0.2     setosa
3               5          3.1           1.5          0.2     setosa
4               5          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145             7          3.0           5.2          2.3  virginica
146             6          2.5           5.0          1.9  virginica
147             6          3.0           5.2          2.0  virginica
148             6          3.4           5.4          2.3  virginica
149             6          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [461]:
df.aggregate('min')

sepal_length         4
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [462]:
df.agg('min')

sepal_length         4
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [464]:
df.agg(['min', 'max', 'median', 'mean'])

<ipython-input-464-025d06ef7e78>:1: FutureWarning: ['species'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.agg(['min', 'max', 'median', 'mean'])


sepal_length  sepal_width  petal_length  petal_width    species
min             4.00        2.000      1.000000     0.100000     setosa
max             8.00        4.400      6.900000     2.500000  virginica
median          6.00        3.000      4.350000     1.300000        NaN
mean            5.86        3.054      3.758667     1.198667        NaN

In [466]:
df.aggregate(['min', 'max', 'mean', 'median'])

<ipython-input-466-ffcb6e11e7e8>:1: FutureWarning: ['species'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.aggregate(['min', 'max', 'mean', 'median'])


sepal_length  sepal_width  petal_length  petal_width    species
min             4.00        2.000      1.000000     0.100000     setosa
max             8.00        4.400      6.900000     2.500000  virginica
mean            5.86        3.054      3.758667     1.198667        NaN
median          6.00        3.000      4.350000     1.300000        NaN

In [469]:
groupby_obj = df.groupby('species')

In [470]:
groupby_obj

In [471]:
groupby_obj.min()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                 4          2.3           1.0          0.1
versicolor             5          2.0           3.0          1.0
virginica              5          2.2           4.5          1.4

In [472]:
groupby_obj.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [473]:
groupby_obj.corr()

sepal_length  sepal_width  petal_length  petal_width
species                                                                      
setosa     sepal_length      1.000000     0.652096      0.182252     0.126412
           sepal_width       0.652096     1.000000      0.176695     0.279973
           petal_length      0.182252     0.176695      1.000000     0.306308
           petal_width       0.126412     0.279973      0.306308     1.000000
versicolor sepal_length      1.000000     0.458796      0.609492     0.377180
           sepal_width       0.458796     1.000000      0.560522     0.663999
           petal_length      0.609492     0.560522      1.000000     0.786668
           petal_width       0.377180     0.663999      0.786668     1.000000
virginica  sepal_length      1.000000     0.387986      0.815619     0.333739
           sepal_width       0.387986     1.000000      0.401045     0.537728
           petal_length      0.815619     0.401045      1.000000     0.322108
           petal_width       0.333739     0.537728      0.322108     1.000000

In [474]:
groupby_obj.sum()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               250        170.9          73.2         12.2
versicolor           302        138.5         213.0         66.3
virginica            327        148.7         277.6        101.3

In [475]:
groupby_obj.mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa              5.00        3.418         1.464        0.244
versicolor          6.04        2.770         4.260        1.326
virginica           6.54        2.974         5.552        2.026

In [481]:
df[df.species=='setosa']['sepal_width'].mean()

3.418

In [484]:
groupby_obj.describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.000000    6.040000   6.540000
             std     0.451754    0.532993   0.734291
             min     4.000000    5.000000   5.000000
             25%     5.000000    6.000000   6.000000
             50%     5.000000    6.000000   6.000000
             75%     5.000000    6.000000   7.000000
             max     6.000000    7.000000   8.000000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

In [487]:
df.species.apply(lambda x:x.upper())

0         SETOSA
1         SETOSA
2         SETOSA
3         SETOSA
4         SETOSA
         ...    
145    VIRGINICA
146    VIRGINICA
147    VIRGINICA
148    VIRGINICA
149    VIRGINICA
Name: species, Length: 150, dtype: object

In [488]:
# Handling missing data

In [489]:
import numpy as np

In [492]:
idx = np.random.randint(1,100, 15)

In [495]:
import warnings
warnings.filterwarnings('ignore')

In [496]:
df.sepal_length[idx] = np.nan

In [497]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.0          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             5.0          3.2           1.3          0.2     setosa
3             5.0          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           7.0          3.0           5.2          2.3  virginica
146           6.0          2.5           5.0          1.9  virginica
147           6.0          3.0           5.2          2.0  virginica
148           6.0          3.4           5.4          2.3  virginica
149           6.0          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [502]:
idx = np.random.randint(1,100,20)

In [504]:
df.petal_length[idx] = np.nan

In [505]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.0          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             5.0          3.2           1.3          0.2     setosa
3             5.0          3.1           1.5          0.2     setosa
4             5.0          3.6           NaN          0.2     setosa
..            ...          ...           ...          ...        ...
145           7.0          3.0           5.2          2.3  virginica
146           6.0          2.5           5.0          1.9  virginica
147           6.0          3.0           5.2          2.0  virginica
148           6.0          3.4           5.4          2.3  virginica
149           6.0          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [507]:
df.isnull().sum()

sepal_length    14
sepal_width      0
petal_length    19
petal_width      0
species          0
dtype: int64

In [509]:
#df.dropna()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.0          3.5           1.4          0.2     setosa
2             5.0          3.2           1.3          0.2     setosa
3             5.0          3.1           1.5          0.2     setosa
5             5.0          3.9           1.7          0.4     setosa
8             4.0          2.9           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           7.0          3.0           5.2          2.3  virginica
146           6.0          2.5           5.0          1.9  virginica
147           6.0          3.0           5.2          2.0  virginica
148           6.0          3.4           5.4          2.3  virginica
149           6.0          3.0           5.1          1.8  virginica

[117 rows x 5 columns]

In [510]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.0          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             5.0          3.2           1.3          0.2     setosa
3             5.0          3.1           1.5          0.2     setosa
4             5.0          3.6           NaN          0.2     setosa
..            ...          ...           ...          ...        ...
145           7.0          3.0           5.2          2.3  virginica
146           6.0          2.5           5.0          1.9  virginica
147           6.0          3.0           5.2          2.0  virginica
148           6.0          3.4           5.4          2.3  virginica
149           6.0          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [512]:
df.fillna('this')

sepal_length  sepal_width petal_length  petal_width    species
0            5.0          3.5          1.4          0.2     setosa
1           this          3.0          1.4          0.2     setosa
2            5.0          3.2          1.3          0.2     setosa
3            5.0          3.1          1.5          0.2     setosa
4            5.0          3.6         this          0.2     setosa
..           ...          ...          ...          ...        ...
145          7.0          3.0          5.2          2.3  virginica
146          6.0          2.5          5.0          1.9  virginica
147          6.0          3.0          5.2          2.0  virginica
148          6.0          3.4          5.4          2.3  virginica
149          6.0          3.0          5.1          1.8  virginica

[150 rows x 5 columns]

In [516]:
df.sepal_length.fillna(value='sanjay')[:50]

0        5.0
1     sanjay
2        5.0
3        5.0
4        5.0
5        5.0
6     sanjay
7        5.0
8        4.0
9        5.0
10       5.0
11       5.0
12       5.0
13       4.0
14    sanjay
15       6.0
16       5.0
17       5.0
18    sanjay
19       5.0
20       5.0
21       5.0
22       5.0
23       5.0
24       5.0
25       5.0
26       5.0
27       5.0
28    sanjay
29       5.0
30       5.0
31    sanjay
32       5.0
33       6.0
34       5.0
35    sanjay
36       6.0
37       5.0
38       4.0
39       5.0
40       5.0
41       4.0
42       4.0
43       5.0
44    sanjay
45       5.0
46       5.0
47       5.0
48       5.0
49       5.0
Name: sepal_length, dtype: object

In [521]:
round(df.sepal_length.mean(), 2)

5.88

In [524]:
df.sepal_length.fillna(value=round(df.sepal_length.mean(), 2), inplace=True)

In [527]:
df['sepal_length'][:50]

0     5.00
1     5.88
2     5.00
3     5.00
4     5.00
5     5.00
6     5.88
7     5.00
8     4.00
9     5.00
10    5.00
11    5.00
12    5.00
13    4.00
14    5.88
15    6.00
16    5.00
17    5.00
18    5.88
19    5.00
20    5.00
21    5.00
22    5.00
23    5.00
24    5.00
25    5.00
26    5.00
27    5.00
28    5.88
29    5.00
30    5.00
31    5.88
32    5.00
33    6.00
34    5.00
35    5.88
36    6.00
37    5.00
38    4.00
39    5.00
40    5.00
41    4.00
42    4.00
43    5.00
44    5.88
45    5.00
46    5.00
47    5.00
48    5.00
49    5.00
Name: sepal_length, dtype: float64

In [532]:
round(df.petal_length.mean(),2)

3.84

In [535]:
df.petal_length = df.petal_length.fillna(value=round(df.petal_length.mean(),2))

In [536]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0            5.00          3.5          1.40          0.2     setosa
1            5.88          3.0          1.40          0.2     setosa
2            5.00          3.2          1.30          0.2     setosa
3            5.00          3.1          1.50          0.2     setosa
4            5.00          3.6          3.84          0.2     setosa
..            ...          ...           ...          ...        ...
145          7.00          3.0          5.20          2.3  virginica
146          6.00          2.5          5.00          1.9  virginica
147          6.00          3.0          5.20          2.0  virginica
148          6.00          3.4          5.40          2.3  virginica
149          6.00          3.0          5.10          1.8  virginica

[150 rows x 5 columns]

In [538]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [539]:
# concat/ merge dataframes

In [545]:
new_df = pd.DataFrame(np.random.randint(0,7, (10,4)))

In [548]:
new_df['species']  = 'new-species14'


In [549]:
new_df

0  1  2  3        species
0  5  4  4  0  new-species14
1  4  5  2  6  new-species14
2  6  2  1  4  new-species14
3  1  4  3  4  new-species14
4  1  4  4  5  new-species14
5  4  0  5  3  new-species14
6  2  3  1  6  new-species14
7  4  4  4  4  new-species14
8  1  4  0  6  new-species14
9  4  0  3  2  new-species14

In [550]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [552]:
new_df.columns = df.columns

In [553]:
new_df

sepal_length  sepal_width  petal_length  petal_width        species
0             5            4             4            0  new-species14
1             4            5             2            6  new-species14
2             6            2             1            4  new-species14
3             1            4             3            4  new-species14
4             1            4             4            5  new-species14
5             4            0             5            3  new-species14
6             2            3             1            6  new-species14
7             4            4             4            4  new-species14
8             1            4             0            6  new-species14
9             4            0             3            2  new-species14

In [556]:
df1 = pd.concat((df,new_df))

In [557]:
df1.shape

(160, 5)

In [558]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width species
0          5.00          3.5          1.40          0.2  setosa
1          5.88          3.0          1.40          0.2  setosa
2          5.00          3.2          1.30          0.2  setosa
3          5.00          3.1          1.50          0.2  setosa
4          5.00          3.6          3.84          0.2  setosa

In [560]:
df2 = pd.concat((df,new_df), axis=1)

In [561]:
df2

sepal_length  sepal_width  petal_length  petal_width    species  \
0            5.00          3.5          1.40          0.2     setosa   
1            5.88          3.0          1.40          0.2     setosa   
2            5.00          3.2          1.30          0.2     setosa   
3            5.00          3.1          1.50          0.2     setosa   
4            5.00          3.6          3.84          0.2     setosa   
..            ...          ...           ...          ...        ...   
145          7.00          3.0          5.20          2.3  virginica   
146          6.00          2.5          5.00          1.9  virginica   
147          6.00          3.0          5.20          2.0  virginica   
148          6.00          3.4          5.40          2.3  virginica   
149          6.00          3.0          5.10          1.8  virginica   

     sepal_length  sepal_width  petal_length  petal_width        species  
0             5.0          4.0           4.0          0.0  new-species14  
1             4.0          5.0           2.0          6.0  new-species14  
2             6.0          2.0           1.0          4.0  new-species14  
3             1.0          4.0           3.0          4.0  new-species14  
4             1.0          4.0           4.0          5.0  new-species14  
..            ...          ...           ...          ...            ...  
145           NaN          NaN           NaN          NaN            NaN  
146           NaN          NaN           NaN          NaN            NaN  
147           NaN          NaN           NaN          NaN            NaN  
148           NaN          NaN           NaN          NaN            NaN  
149           NaN          NaN           NaN          NaN            NaN  

[150 rows x 10 columns]

In [562]:
df2.shape

(150, 10)

In [563]:
# merging dataframes

In [565]:
df1 = pd.DataFrame({
    'S_Name':['Mohit', 'Jatin', 'Prateek', 'Mohit'],
    'CGPA':[2,4,5,3]
})

In [566]:
df1

S_Name  CGPA
0    Mohit     2
1    Jatin     4
2  Prateek     5
3    Mohit     3

In [567]:
df2 = pd.DataFrame({
    'T_Name':["Mohit",'Jatin' ,'Prateek', 'Mohit'],
    'CGPA':[3,6,8,9]
})

In [568]:
df2

T_Name  CGPA
0    Mohit     3
1    Jatin     6
2  Prateek     8
3    Mohit     9

In [569]:
df1.merge(df2)

S_Name  CGPA T_Name
0  Mohit     3  Mohit

In [570]:
df1.merge(df2, how='left')

S_Name  CGPA T_Name
0    Mohit     2    NaN
1    Jatin     4    NaN
2  Prateek     5    NaN
3    Mohit     3  Mohit

In [571]:
df1.merge(df2, how='right')

S_Name  CGPA   T_Name
0  Mohit     3    Mohit
1    NaN     6    Jatin
2    NaN     8  Prateek
3    NaN     9    Mohit

In [572]:
df1.merge(df2, how='cross')

S_Name  CGPA_x   T_Name  CGPA_y
0     Mohit       2    Mohit       3
1     Mohit       2    Jatin       6
2     Mohit       2  Prateek       8
3     Mohit       2    Mohit       9
4     Jatin       4    Mohit       3
5     Jatin       4    Jatin       6
6     Jatin       4  Prateek       8
7     Jatin       4    Mohit       9
8   Prateek       5    Mohit       3
9   Prateek       5    Jatin       6
10  Prateek       5  Prateek       8
11  Prateek       5    Mohit       9
12    Mohit       3    Mohit       3
13    Mohit       3    Jatin       6
14    Mohit       3  Prateek       8
15    Mohit       3    Mohit       9

In [573]:
df1.merge(df2, how='outer', on='CGPA')

S_Name  CGPA   T_Name
0    Mohit     2      NaN
1    Jatin     4      NaN
2  Prateek     5      NaN
3    Mohit     3    Mohit
4      NaN     6    Jatin
5      NaN     8  Prateek
6      NaN     9    Mohit

In [576]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [578]:
df.to_csv('my_15_data.csv', index=False)

In [580]:
modified_csv= pd.read_csv('my_15_data.csv')

In [581]:
modified_csv.head()

sepal_length  sepal_width  petal_length  petal_width species
0          5.00          3.5          1.40          0.2  setosa
1          5.88          3.0          1.40          0.2  setosa
2          5.00          3.2          1.30          0.2  setosa
3          5.00          3.1          1.50          0.2  setosa
4          5.00          3.6          3.84          0.2  setosa

In [584]:
df.to_excel('my_15_excel.xlsx',sheet_name='sales_data' ,index=False)